name: kodanka
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - attrs=19.3.0
  - babel=2.8.0
  - backcall=0.1.0
  - bleach=3.1.4
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.8
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - idna=2.9
  - imagesize=1.2.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - ipykernel=5.2.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.2
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=6.1.2
  - jupyter_core=4.6.3
  - jupyterlab=2.1.0
  - jupyterlab_server=1.1.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libsodium=1.0.17
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - nbsphinx=0.6.0
  - ncurses=6.2
  - notebook=6.0.3
  - openssl=1.1.1f
  - packaging=20.1
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - pyzmq=19.0.0
  - readline=8.0
  - requests=2.23.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sphinx=3.0.1
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.8
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11

